complexity:
  LongParameterList:
    ignoreDefaultParameters: true
    functionThreshold: 20
  LongMethod:
    active: false
  CyclomaticComplexMethod:
    threshold: 30

style:
  MagicNumber:
    active: false
    ignorePropertyDeclaration: true
    ignoreCompanionObjectPropertyDeclaration: true
  UnusedPrivateMember:
    ignoreAnnotated: [ 'preview' ]
  ThrowsCount:
    active: true
    max: 10

naming:
  TopLevelPropertyNaming:
    constantPattern: '[A-Z][A-Za-z0-9]*'
  FunctionNaming:
    ignoreAnnotated: [ 'Composable' ]
  
exceptions:
  TooGenericExceptionThrown:
    active: false
  SwallowedException:
    active: false